export const GET_INCIDENT_SUCCESS = "GET_INCIDENT_SUCCESS";
export const GET_INCIDENT_ERROR = "GET_INCIDENT_ERROR";
export const GET_INCIDENTS_SUCCESS = "GET_INCIDENTS_SUCCESS";
export const GET_INCIDENTS_ERROR = "GET_INCIDENTS_ERROR";
export const CREATE_INCIDENT_SUCCESS = "CREATE_INCIDENT_SUCCESS";
export const CREATE_INCIDENT_ERROR = "CREATE_INCIDENT_ERROR";
